/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package phisco.streams.polimi.it.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SJSONTripleMap extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5920923925971873944L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SJSONTripleMap\",\"namespace\":\"phisco.streams.polimi.it.avro\",\"fields\":[{\"name\":\"data\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SJSONTriple\",\"fields\":[{\"name\":\"s\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"p\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"o\",\"type\":{\"type\":\"record\",\"name\":\"TripleObject\",\"fields\":[{\"name\":\"value\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"},\"int\",\"long\",\"float\"]},{\"name\":\"datatype\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"Kind\",\"symbols\":[\"literal\",\"uri\",\"bnode\"]}}]}},{\"name\":\"ts\",\"type\":\"long\"}]}},\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SJSONTripleMap> ENCODER =
      new BinaryMessageEncoder<SJSONTripleMap>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SJSONTripleMap> DECODER =
      new BinaryMessageDecoder<SJSONTripleMap>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<SJSONTripleMap> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<SJSONTripleMap> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SJSONTripleMap>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this SJSONTripleMap to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a SJSONTripleMap from a ByteBuffer. */
  public static SJSONTripleMap fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.Map<java.lang.String,java.util.List<phisco.streams.polimi.it.avro.SJSONTriple>> data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SJSONTripleMap() {}

  /**
   * All-args constructor.
   * @param data The new value for data
   */
  public SJSONTripleMap(java.util.Map<java.lang.String,java.util.List<phisco.streams.polimi.it.avro.SJSONTriple>> data) {
    this.data = data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: data = (java.util.Map<java.lang.String,java.util.List<phisco.streams.polimi.it.avro.SJSONTriple>>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.util.Map<java.lang.String,java.util.List<phisco.streams.polimi.it.avro.SJSONTriple>> getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.util.Map<java.lang.String,java.util.List<phisco.streams.polimi.it.avro.SJSONTriple>> value) {
    this.data = value;
  }

  /**
   * Creates a new SJSONTripleMap RecordBuilder.
   * @return A new SJSONTripleMap RecordBuilder
   */
  public static phisco.streams.polimi.it.avro.SJSONTripleMap.Builder newBuilder() {
    return new phisco.streams.polimi.it.avro.SJSONTripleMap.Builder();
  }

  /**
   * Creates a new SJSONTripleMap RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SJSONTripleMap RecordBuilder
   */
  public static phisco.streams.polimi.it.avro.SJSONTripleMap.Builder newBuilder(phisco.streams.polimi.it.avro.SJSONTripleMap.Builder other) {
    return new phisco.streams.polimi.it.avro.SJSONTripleMap.Builder(other);
  }

  /**
   * Creates a new SJSONTripleMap RecordBuilder by copying an existing SJSONTripleMap instance.
   * @param other The existing instance to copy.
   * @return A new SJSONTripleMap RecordBuilder
   */
  public static phisco.streams.polimi.it.avro.SJSONTripleMap.Builder newBuilder(phisco.streams.polimi.it.avro.SJSONTripleMap other) {
    return new phisco.streams.polimi.it.avro.SJSONTripleMap.Builder(other);
  }

  /**
   * RecordBuilder for SJSONTripleMap instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SJSONTripleMap>
    implements org.apache.avro.data.RecordBuilder<SJSONTripleMap> {

    private java.util.Map<java.lang.String,java.util.List<phisco.streams.polimi.it.avro.SJSONTriple>> data;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(phisco.streams.polimi.it.avro.SJSONTripleMap.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SJSONTripleMap instance
     * @param other The existing instance to copy.
     */
    private Builder(phisco.streams.polimi.it.avro.SJSONTripleMap other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.util.List<phisco.streams.polimi.it.avro.SJSONTriple>> getData() {
      return data;
    }

    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public phisco.streams.polimi.it.avro.SJSONTripleMap.Builder setData(java.util.Map<java.lang.String,java.util.List<phisco.streams.polimi.it.avro.SJSONTriple>> value) {
      validate(fields()[0], value);
      this.data = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public phisco.streams.polimi.it.avro.SJSONTripleMap.Builder clearData() {
      data = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SJSONTripleMap build() {
      try {
        SJSONTripleMap record = new SJSONTripleMap();
        record.data = fieldSetFlags()[0] ? this.data : (java.util.Map<java.lang.String,java.util.List<phisco.streams.polimi.it.avro.SJSONTriple>>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SJSONTripleMap>
    WRITER$ = (org.apache.avro.io.DatumWriter<SJSONTripleMap>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SJSONTripleMap>
    READER$ = (org.apache.avro.io.DatumReader<SJSONTripleMap>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
