/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package phisco.streams.polimi.it.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class URI extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1550411936125114225L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"URI\",\"namespace\":\"phisco.streams.polimi.it.avro\",\"fields\":[{\"name\":\"value\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"URIKind\",\"symbols\":[\"uri\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<URI> ENCODER =
      new BinaryMessageEncoder<URI>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<URI> DECODER =
      new BinaryMessageDecoder<URI>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<URI> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<URI> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<URI>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this URI to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a URI from a ByteBuffer. */
  public static URI fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String value;
  @Deprecated public phisco.streams.polimi.it.avro.URIKind type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public URI() {}

  /**
   * All-args constructor.
   * @param value The new value for value
   * @param type The new value for type
   */
  public URI(java.lang.String value, phisco.streams.polimi.it.avro.URIKind type) {
    this.value = value;
    this.type = type;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    case 1: return type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (java.lang.String)value$; break;
    case 1: type = (phisco.streams.polimi.it.avro.URIKind)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.String getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.String value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public phisco.streams.polimi.it.avro.URIKind getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(phisco.streams.polimi.it.avro.URIKind value) {
    this.type = value;
  }

  /**
   * Creates a new URI RecordBuilder.
   * @return A new URI RecordBuilder
   */
  public static phisco.streams.polimi.it.avro.URI.Builder newBuilder() {
    return new phisco.streams.polimi.it.avro.URI.Builder();
  }

  /**
   * Creates a new URI RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new URI RecordBuilder
   */
  public static phisco.streams.polimi.it.avro.URI.Builder newBuilder(phisco.streams.polimi.it.avro.URI.Builder other) {
    return new phisco.streams.polimi.it.avro.URI.Builder(other);
  }

  /**
   * Creates a new URI RecordBuilder by copying an existing URI instance.
   * @param other The existing instance to copy.
   * @return A new URI RecordBuilder
   */
  public static phisco.streams.polimi.it.avro.URI.Builder newBuilder(phisco.streams.polimi.it.avro.URI other) {
    return new phisco.streams.polimi.it.avro.URI.Builder(other);
  }

  /**
   * RecordBuilder for URI instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<URI>
    implements org.apache.avro.data.RecordBuilder<URI> {

    private java.lang.String value;
    private phisco.streams.polimi.it.avro.URIKind type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(phisco.streams.polimi.it.avro.URI.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing URI instance
     * @param other The existing instance to copy.
     */
    private Builder(phisco.streams.polimi.it.avro.URI other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.String getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public phisco.streams.polimi.it.avro.URI.Builder setValue(java.lang.String value) {
      validate(fields()[0], value);
      this.value = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public phisco.streams.polimi.it.avro.URI.Builder clearValue() {
      value = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public phisco.streams.polimi.it.avro.URIKind getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public phisco.streams.polimi.it.avro.URI.Builder setType(phisco.streams.polimi.it.avro.URIKind value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public phisco.streams.polimi.it.avro.URI.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public URI build() {
      try {
        URI record = new URI();
        record.value = fieldSetFlags()[0] ? this.value : (java.lang.String) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (phisco.streams.polimi.it.avro.URIKind) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<URI>
    WRITER$ = (org.apache.avro.io.DatumWriter<URI>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<URI>
    READER$ = (org.apache.avro.io.DatumReader<URI>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
