package phisco.streams.polimi.it.avro;
/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum URIKind {
  uri  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"URIKind\",\"symbols\":[\"uri\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
